name: github pages

on:
  push:
    branches:
        - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test
        run: deno test
